services:
  database:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql-volume:/var/lib/mysql
  cache:
    image: 'redis:latest'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  api:
    build: .
    restart: always
    depends_on:
      cache:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
      - ./templates/:/app/templates
    ports:
      - '3000:3000'